// Mac 版用 SF Symbols；这里按同名映射到 lucide 图标，移植过来的代码可以照抄符号名。
import type { CSSProperties } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowDownCircle,
  ArrowUp,
  ArrowUpRight,
  BarChart3,
  Brain,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  Clock,
  Coffee,
  Copy,
  Cpu,
  Flame,
  Folder,
  FolderOpen,
  Gauge,
  Globe,
  Hexagon,
  History,
  Images,
  Info,
  Key,
  Layers,
  LineChart,
  Link,
  Lock,
  MessageSquare,
  Moon,
  PieChart,
  Power,
  Radio,
  RefreshCw,
  RotateCw,
  Server,
  Settings,
  Shield,
  Sparkles,
  Star,
  Terminal,
  Timer,
  Trash2,
  TrendingUp,
  User,
  Users,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "dollarsign.circle": CircleDollarSign,
  "arrow.down": ArrowDown,
  "arrow.up": ArrowUp,
  "arrow.up.right": ArrowUpRight,
  "bolt.fill": Zap,
  "square.stack.3d.up.fill": Layers,
  brain: Brain,
  "gauge.medium": Gauge,
  timer: Timer,
  "circle.hexagongrid.fill": Hexagon,
  "chart.pie.fill": PieChart,
  "chevron.down": ChevronDown,
  "chevron.right": ChevronRight,
  "info.circle": Info,
  "info.circle.fill": Info,
  clock: Clock,
  "clock.arrow.circlepath": History,
  "exclamationmark.triangle.fill": AlertTriangle,
  "exclamationmark.triangle": AlertTriangle,
  "arrow.clockwise.circle.fill": RefreshCw,
  "arrow.clockwise": RotateCw,
  "arrow.triangle.2.circlepath": RefreshCw,
  "arrow.down.circle": ArrowDownCircle,
  "arrow.down.circle.fill": ArrowDownCircle,
  folder: Folder,
  "folder.fill": FolderOpen,
  "chart.xyaxis.line": LineChart,
  "chart.bar": BarChart3,
  "chart.line.uptrend.xyaxis": TrendingUp,
  gearshape: Settings,
  "gearshape.fill": Settings,
  "photo.on.rectangle": Images,
  checkmark: Check,
  "checkmark.circle.fill": CheckCircle2,
  power: Power,
  "dot.radiowaves.left.and.right": Radio,
  "cup.and.saucer": Coffee,
  "cup.and.saucer.fill": Coffee,
  "moon.zzz": Moon,
  "doc.on.doc": Copy,
  key: Key,
  "key.fill": Key,
  lock: Lock,
  "lock.shield": Shield,
  globe: Globe,
  link: Link,
  terminal: Terminal,
  server: Server,
  "server.rack": Server,
  cpu: Cpu,
  "person.fill": User,
  "person.2.fill": Users,
  "bubble.left.fill": MessageSquare,
  "flame.fill": Flame,
  "star.fill": Star,
  sparkles: Sparkles,
  "wrench.and.screwdriver": Wrench,
  calendar: Calendar,
  trash: Trash2,
  xmark: X,
  "waveform.path.ecg": Activity,
};

export function Icon({
  name,
  size = 12,
  color,
  strokeWidth = 2.2,
  style,
}: {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: CSSProperties;
}) {
  const Component = MAP[name] ?? Info;
  return <Component size={size} color={color ?? "currentColor"} strokeWidth={strokeWidth} style={style} />;
}
